---

- name: install haproxy
  yum:
    name: haproxy
    state: present

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
    validate: 'haproxy -f %s -c'
  notify: restart haproxy

- name: enable haproxy across reboots
  service:
    enabled: true
    name: haproxy
    state: started

...
