---

- name: install nginx
  yum:
    name: nginx
    state: present

- name: update nginx config file - /etc/nginx/nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "u=wr,go=r"
  notify: restart nginx

- name: update nginx config file - /etc/nginx/conf.d/default.conf
  template:
    src: conf.d-default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: "u=wr,go=r"
  notify: restart nginx

- name: update nginx content file - index.html
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: "u=wr,go=r"
  notify: restart nginx

- name: enable nginx across reboots
  service:
    name: nginx
    enabled: true
    state: started

...
